blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/your-org/ai-it-project-process-management-webapp/blob/main/README.md
    about: Please check our documentation before creating an issue
  - name: 💬 Discussion Forum
    url: https://github.com/your-org/ai-it-project-process-management-webapp/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🆘 Support
    url: mailto:dev-team@company.com
    about: Contact the development team for urgent support
